* QuestRunner

An android application that gives you custom quests to inspire your run.

* TODO Things
- App
  - [ ] Fix serialization bugs from new prod release
  - [ ] Finish complete run page
  - [ ] List personal quests
  - [ ] Create a quest page
  - [ ] Gps/ custom map markings (from locations in story)
  - [ ] Push up git repo
  - [ ] Add a page to list out tag type songs to just stream music for run.
  - [ ] Show the details of the dialog/music you are on currently.
    
- API
  - [X] Reuse songs in dialog list
  - [X] Make sure dialog list saves name, tag, author.. Or maybe split up songs from dialogs list and glue them together on serialization
  - [X] songs in a quest should not double up, it should at least pick one of every song before cycling back through. 
  - [ ] Serve up map tiles based off tags/ or have a go exe to generate map array AND new map image.
  - [X] FIX BUG, dialog list url is saving wrong because tag.__str__ is not correct, it needs to be .name.. I think its fixed but not prod.
    
- Backend
  - [ ] add DB collapse on dialogs/dialog lists to deleted quests
  - [ ] Create a story location finder (read story find location mentioned)
  - [ ] Impliment a non AI story generator
  - [ ] add images to song dialog lists
  - [ ] Add map generation (per quest/adventure)
  - [X] new django command to load statif files into django static objects that will point to dialog lists
  - [ ] see if its possible to move to golang/clisp/elixir
    
- Site

  - [ ] Add a website, with the ability to view/play the game & make prompts
  - [ ] on a site add the ability to make your own prompts from your own music/ custom written dialog.

- Genres
  - [X] Scifi
  - [ ] western
  - [ ] noir
  - [ ] world war 2
  - [ ] scifi war
  - [ ] war stories


- Game 
  - [ ] I want to impliment a game into the android app
  - [ ] Add quest completion game rewards/currency
  - [ ] play with littlekt vs korge
  - [ ] I want to impliment a game currency in the app, that is used to generate quests

- Others
  - [ ] Maybe add prompts to generate stories for other forms of exersize. bicycling or lifting weights




