# Generated by Django 5.0.6 on 2024-06-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='uuid',
            field=models.CharField(default='', max_length=125),
        ),
    ]
