# Generated by Django 5.0.6 on 2024-06-08 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_quest_questrun_delete_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('url', models.CharField(default='', max_length=255)),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogs', to='common.quest')),
            ],
        ),
    ]
