# Generated by Django 5.0.6 on 2024-06-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_quest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quest',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
