# Generated by Django 5.0.6 on 2024-06-15 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_quest_public_quest_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rated_quest', to='common.quest')),
            ],
        ),
    ]
