# Generated by Django 5.0.6 on 2024-06-28 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_questrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='dialoglist',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dialoglist',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quest',
            name='genre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quest',
            name='next_quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_quest', to='common.quest'),
        ),
        migrations.AddField(
            model_name='questrun',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0.0)),
                ('genre', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_adventures', to=settings.AUTH_USER_MODEL)),
                ('starting_quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_adventure', to='common.quest')),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adventure_tags', to='common.tag')),
            ],
        ),
        migrations.AddField(
            model_name='dialoglist',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialog_tags', to='common.tag'),
        ),
        migrations.AddField(
            model_name='quest',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_tags', to='common.tag'),
        ),
        migrations.DeleteModel(
            name='QuestRating',
        ),
    ]
