# Generated by Django 5.0.6 on 2024-06-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_tag_dialoglist_author_dialoglist_name_quest_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='prompt',
            field=models.CharField(default='', max_length=255),
        ),
    ]
