# Generated by Django 5.0.6 on 2024-06-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_tag_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='genre',
        ),
    ]
