# Generated by Django 5.0.6 on 2024-07-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_remove_quest_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialoglist',
            name='quest',
        ),
        migrations.AddField(
            model_name='dialoglist',
            name='quests',
            field=models.ManyToManyField(related_name='dialogs', to='common.quest'),
        ),
    ]
