# Generated by Django 5.0.6 on 2024-07-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_remove_dialoglist_quest_dialoglist_quests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dialoglist",
            name="author",
        ),
        migrations.RemoveField(
            model_name="dialoglist",
            name="index",
        ),
        migrations.RemoveField(
            model_name="dialoglist",
            name="name",
        ),
        migrations.RemoveField(
            model_name="dialoglist",
            name="quests",
        ),
        migrations.RemoveField(
            model_name="dialoglist",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="dialoglist",
            name="url",
        ),
        migrations.AddField(
            model_name="dialoglist",
            name="dlist",
            field=models.TextField(default="[]"),
        ),
        migrations.AddField(
            model_name="dialoglist",
            name="quest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dialog_list",
                to="common.quest",
            ),
        ),
        migrations.CreateModel(
            name="Dialog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField(default=0)),
                ("url", models.CharField(default="", max_length=255)),
                (
                    "quest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dialogs",
                        to="common.quest",
                    ),
                ),
                (
                    "tags",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dialog_tags",
                        to="common.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(default="", max_length=255)),
                ("name", models.CharField(default="", max_length=255)),
                ("author", models.CharField(default="", max_length=255)),
                ("image", models.CharField(default="", max_length=255)),
                (
                    "tags",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="song_tags",
                        to="common.tag",
                    ),
                ),
            ],
        ),
    ]
