# Generated by Django 5.0.6 on 2024-07-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_remove_dialoglist_author_remove_dialoglist_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='fname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
